const allGenres = [
    "Health & Fitness",
    "Relationships",
    "Psycology",
    "Financial",
    "Career",
    "Education",
    "Entrepreneurship",
    "Politics",
    "Diet",
    "Fashion",
    "Family",
    "Pets",
    "Medicine",
    "Cooking",
    "Movies",
    "Music",
    "Games",
    "Vehicals",
    "Plants",
    "Yoga",
    "Culture",
    "Dancing",
    "Spiritual",
    "Technology",
    "Coding",
    "Traveling",
  ];

  export {allGenres}